services:
  web:
    build: .
    command: npm start
    port: 3000
    scale:
      count: 1
      cpu: 128
      memory: 256
    ingressAnnotations:
      - nginx.ingress.kubernetes.io/limit-rpm=10
      - nginx.ingress.kubernetes.io/enable-access-log=false
    health:
      grace: 10
      interval: 5
      path: /check
      timeout: 3
balancers:
  ingress:
    annotations:
    - service.beta.kubernetes.io/aws-load-balancer-scheme=internal
    - service.beta.kubernetes.io/aws-load-balancer-internal=true
    - service.beta.kubernetes.io/aws-load-balancer-type=nlb
    - service.beta.kubernetes.io/aws-load-balancer-additional-resource-tags=Service=web
    service: web
    ports:
      80: 3000
